# -*- coding: utf-8 -*-
"""Rating Calculation Script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DfLDtXieJk8Snm_0a0YCIVLxwmzXMvSG
"""

# Inisialisasi variabel global untuk menyimpan nilai
x = None
b5 = None
b4 = None
b3 = None
b2 = None
b1 = None

def kalkulasi():
    global x, b5, b4, b3, b2, b1

    while True:
        while True:
            # Memilih opsi
            print("Choose an option:")
            print("1. Enter initial value")
            print("2. Enter the vote you want to add")
            print("3. Exit")
            print("4. Clear the screen")
            choice = input("Enter your choice (1/2/3/4): ")


            if choice == '1':
                # Input jumlah review
                x = int(input("Enter the current total rating: "))  # Current Total Rating

                # Input number of votes for each rating
                b5 = int(input("Enter the number of votes for 5 stars: "))  # Input B5
                b4 = int(input("Enter the number of votes for 4 stars: "))  # Input B4
                b3 = int(input("Enter the number of votes for 3 stars: "))  # Input B3
                b2 = int(input("Enter the number of votes for 2 stars: "))  # Input B2
                b1 = int(input("Enter the number of votes for 1 star: "))  # Input B1

                rating_awal = (5 * b5 + 4 * b4 + 3 * b3 + 2 * b2 + 1 * b1) / x
                total_votes = b5 + b4 + b3 + b2 + b1
                if x != total_votes:
                    print("Total of b5, b4, b3, b2, and b1 does not equal the total rating (x). Please try again.")
                    continue
                # Hitung rating saat ini
                current_rating = (5 * b5 + 4 * b4 + 3 * b3 + 2 * b2 + 1 * b1) / total_votes
                print("===========================")
                print(f"Initial Rating: {current_rating:.2f}")
                print("===========================")

                # Lanjut ke mengisi vote tambahan
                break
            elif choice == '2':
                if x is None or b5 is None or b4 is None or b3 is None or b2 is None or b1 is None:
                    print("Please fill in the values ​​from the beginning first.")
                    continue

                # Input tambahan vote untuk setiap bintang
                additional_votes_b5 = int(input("Enter additional votes for 5 stars: "))
                additional_votes_b4 = int(input("Enter additional votes for 4 stars: "))
                additional_votes_b3 = int(input("Enter additional votes for 3 stars: "))
                additional_votes_b2 = int(input("Enter additional votes for 2 stars: "))
                additional_votes_b1 = int(input("Enter additional votes for 1 stars: "))

                # Kalkulasi total vote setelah penambahan
                total_votes_after_addition = (b5 + additional_votes_b5 + b4 + additional_votes_b4 +
                                              b3 + additional_votes_b3 + b2 + additional_votes_b2 +
                                              b1 + additional_votes_b1)

                # Kalkulasi total rating setelah penambahan
                total_rating = (5 * (b5 + additional_votes_b5) + 4 * (b4 + additional_votes_b4) +
                                3 * (b3 + additional_votes_b3) + 2 * (b2 + additional_votes_b2) +
                                1 * (b1 + additional_votes_b1)) / total_votes_after_addition

                # Tampilkan total rating setelah penambahan
                print("===========================")
                print(f"Total Votes After Addition: {total_votes_after_addition}")
                print(f"Total Rating After Addition: {total_rating:.2f}")

                break
            elif choice == '3':
                return
            elif choice == '4':
                # clear_output()
                # Membersihkan layar0
                import os
                os.system('cls' if os.name == 'nt' else 'clear')
                print("The screen has been cleared.")
            else:
                print("Invalid selection. Please select 1, 2, 3, or 4.")

        # Tanyakan apakah ingin mengulang atau tidak
        ulang = input("Do you want to have other operations? (y/n): ").lower()
        if ulang != 'y':
            break

print("===========START===========")
kalkulasi()
print("============END============")
0